AllCops:
  TargetRubyVersion: 4.0
  NewCops: enable

Layout/LineLength:
  Max: 100

Style/FrozenStringLiteralComment:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/OneClassPerFile:
  Exclude:
    - ruby-literacy/fundamentals/variable_naming_rules.rb
    - ruby-literacy/objects_and_classes/define_a_class.rb
    - ruby-literacy/objects_and_classes/setter_methods.rb
    - ruby-literacy/methods_and_inheritance/inheritance.rb
    - ruby-literacy/modules/creating_a_module.rb
    - ruby-literacy/default_object_self_and_scope/scope_and_visibility.rb
    - ruby-literacy/methods_and_inheritance/method_hierarchies.rb
    - ruby-literacy/objects_and_classes/class_variables.rb
    - ruby-literacy/objects_and_classes/class_instance_variables.rb
    - 'ruby-literacy/control_flow_techniques/if_elsif_else.rb'


Style/TrivialAccessors:
  Exclude:
    - programs/setter_and_getter.rb
    - ruby-literacy/objects_and_classes/initialize_obj_with_state.rb
    - ruby-literacy/objects_and_classes/setter_methods.rb

Style/FormatString:
  Exclude:
    - programs/setter_and_getter.rb
    - ruby-literacy/objects_and_classes/setter_methods.rb

Naming/AccessorMethodName:
  Exclude:
    - ruby-literacy/objects_and_classes/instance_var_and_obj_state.rb

Lint/EmptyClass:
  Exclude:
    - ruby-literacy/objects_and_classes/define_a_class.rb

Style/ClassVars:
  Exclude:
    - ruby-literacy/fundamentals/variable_naming_rules.rb
    - ruby-literacy/objects_and_classes/class_variables.rb

Style/GlobalVars:
  Exclude:
    - ruby-literacy/fundamentals/variable_naming_rules.rb
    - ruby-literacy/default_object_self_and_scope/scope_and_visibility.rb

Style/MutableConstant:
  Exclude:
    - ruby-literacy/fundamentals/constants.rb

Style/IfWithBooleanLiteralBranches:
  Exclude:
    - 'ruby-literacy/control_flow_techniques/if_elsif_else.rb'

Style/RedundantConditional:
  Exclude:
    - 'ruby-literacy/control_flow_techniques/if_elsif_else.rb'

Style/UnlessElse:
  Exclude:
    - 'ruby-literacy/control_flow_techniques/if_elsif_else.rb'

Style/NegatedIfElseCondition:
  Exclude:
    - 'ruby-literacy/control_flow_techniques/if_elsif_else.rb'

Style/InverseMethods:
  Exclude:
    - 'ruby-literacy/control_flow_techniques/if_elsif_else.rb'

Lint/DuplicateBranch:
  Exclude:
    - 'ruby-literacy/control_flow_techniques/if_elsif_else.rb'