namespace :programs do
  namespace :clean do
    desc 'Delete generated program output files'
    task :output_files do
      output_pattern = File.join(__dir__, 'output_files', '*.out')
      Dir[output_pattern].each { |file| File.delete(file) }
    end
  end
end
